/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
      },
      colors: {
        primary: "#2563eb",
        secondary: "#10b981",
        accent: "#a855f7",
        "on-background": "#131b2e",
        background: "#faf8ff",
        "on-primary": "#ffffff",
        "primary-container": "#4f46e5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-variant": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#464555",
        outline: "#777587",
        "outline-variant": "#c7c4d8",
        "dark-background": "#0f1420",
        "dark-on-background": "#e2e7ff",
        "dark-surface-container-lowest": "#131b2e",
        "dark-surface-container-low": "#1a2236",
        "dark-surface-container": "#202a42",
        "dark-surface-container-high": "#28324c",
        "dark-surface-variant": "#2e3a56",
        "dark-on-surface-variant": "#c7c4d8",
        "dark-outline": "#8f8da3",
        "dark-outline-variant": "#464555",
        // Warna semantik status — dipakai budget, validasi form, dan tren transaksi.
        // Nilai light dipilih agar >=4.5:1 di atas permukaan terang, nilai dark
        // sengaja lebih terang/desaturasi (bukan warna yang sama) supaya tetap terbaca.
        success: "#047857",
        "success-container": "#d1fae5",
        "dark-success": "#34d399",
        warning: "#a16207",
        "warning-container": "#fef3c7",
        "dark-warning": "#fbbf24",
        danger: "#b91c1c",
        "danger-container": "#fee2e2",
        "dark-danger": "#f87171",
      },
      fontSize: {
        "body-sm": ["0.875rem", { lineHeight: "1.25rem" }],
        "label-sm": ["0.75rem", { lineHeight: "1rem" }],
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        xxl: "64px",
        gutter: "24px",
      },
    },
  },
  darkMode: "class",
  plugins: [],
};
