/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#2563eb",
        secondary: "#10b981",
        accent: "#a855f7",
        "on-background": "#131b2e",
        background: "#faf8ff",
        "on-primary": "#ffffff",
        "primary-container": "#4f46e5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-variant": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#464555",
        outline: "#777587",
        "outline-variant": "#c7c4d8",
        "dark-background": "#0f1420",
        "dark-on-background": "#e2e7ff",
        "dark-surface-container-lowest": "#131b2e",
        "dark-surface-container-low": "#1a2236",
        "dark-surface-container": "#202a42",
        "dark-surface-container-high": "#28324c",
        "dark-surface-variant": "#2e3a56",
        "dark-on-surface-variant": "#c7c4d8",
        "dark-outline": "#8f8da3",
        "dark-outline-variant": "#464555",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        xxl: "64px",
        gutter: "24px",
      },
    },
  },
  darkMode: "class",
  plugins: [],
};
